# Generated by Django 5.1.1 on 2024-09-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProductionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.CharField(default='', max_length=255)),
                ('price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_production_services',
            },
        ),
        migrations.CreateModel(
            name='BookPublishingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('A4', 'A 4'), ('A5', 'A 5'), ('A6', 'A 6'), ('SQUARE', 'Square'), ('B5', 'B 5')], max_length=10)),
                ('circulation', models.IntegerField()),
                ('personal_discount', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_publishing_projects',
            },
        ),
        migrations.CreateModel(
            name='SelectedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('BASE', 'Base'), ('PREMIUM', 'Premium'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_production.bookpublishingproject')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_production.bookproductionservice')),
            ],
            options={
                'db_table': 'selected_services',
                'unique_together': {('project', 'service')},
            },
        ),
    ]
