# Generated by Django 5.1.1 on 2024-09-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpublishingproject',
            name='circulation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublishingproject',
            name='format',
            field=models.CharField(choices=[('A4', 'A 4'), ('A5', 'A 5'), ('A6', 'A 6'), ('SQUARE', 'Square'), ('B5', 'B 5')], default='A4', max_length=10),
        ),
    ]
