# Generated by Django 5.1.1 on 2024-10-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_production', '0002_alter_bookpublishingproject_circulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproductionservice',
            name='image_url',
            field=models.CharField(blank='True', default='', max_length=255, null=True),
        ),
    ]
